stages:
- stage: Build
  displayName: 'Build Frontend & Backend'
  jobs:
  - job: BuildJob
    pool:
      name: SelfHostPool
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Use Node.js 20.x'

    - script: |
        cd Frontend
        npm install
        npm run build
      displayName: 'Build Frontend'

    - script: |
        if not exist Backend\public mkdir Backend\public
        xcopy Frontend\build Backend\public /E /I /Y
      displayName: 'Copy Frontend Build to Backend'

    - script: |
        cd Backend
        if exist node_modules rmdir /s /q node_modules
        powershell -Command "Compress-Archive -Path '*' -DestinationPath '../backend.zip' -Force"
      displayName: 'Package Backend for Deployment'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/backend.zip'
        artifact: 'release'
      displayName: 'Publish Backend Artifact'

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  jobs:
  - deployment: DeployJob
    environment: 'Production'
    pool:
      name: SelfHostPool
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'release'
              targetPath: '$(Pipeline.Workspace)'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'tdas_sc'
              appType: 'webApp'
              appName: 'transportationDelayAlertApp'
              package: '$(Pipeline.Workspace)/backend.zip'

          - script: |
              cd site\wwwroot
              npm install --production
            displayName: 'Install Backend Dependencies on Azure'