trigger:
- main

pool:
  name: 'SelfHostPool'

variables:
  azureServiceConnection: 'AzureFreeTrialConnection'
  webAppName: 'your-webapp-name'
  nodeVersion: '22.x'

steps:
# 1️⃣ Build frontend
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Use Node.js $(nodeVersion)'

- script: |
    cd frontend
    npm install
    npm run build
  displayName: 'Build Frontend'

# 2️⃣ Copy frontend build → backend/public
- script: |
    REM Create backend/public if it doesn't exist
    if not exist backend\public mkdir backend\public

    REM Copy all files from frontend\build to backend\public
    xcopy frontend\build backend\public /E /I /Y
  displayName: 'Copy Frontend Build to Backend'

# 3️⃣ Install backend dependencies
- script: |
    cd backend
    npm install --production
  displayName: 'Install Backend Dependencies'

# 4️⃣ Package backend for deployment
- script: |
    REM Package backend folder into backend.zip
    powershell -Command "Compress-Archive -Path 'backend\*' -DestinationPath 'backend.zip' -Force"
  displayName: 'Package Backend for Deployment'

# 5️⃣ Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    appName: '$(webAppName)'
    package: 'backend.zip'
  displayName: 'Deploy to Azure Web App'