trigger:
- main

pool:
  name: 'SelfHostPool'

variables:
  azureServiceConnection: 'AzureFreeTrialConnection'
  webAppName: 'your-webapp-name'
  nodeVersion: '22.x'

steps:
# 1️⃣ Build frontend
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Use Node.js $(nodeVersion)'

- script: |
    cd frontend
    npm install
    npm run build
  displayName: 'Build Frontend'
  shell: cmd

# 2️⃣ Copy frontend build → backend/public
- powershell: |
    Write-Host "Copying frontend build to backend/public..."
    $src  = "frontend\build\*"
    $dest = "backend\public"
    if (Test-Path $dest) { Remove-Item $dest -Recurse -Force }
    New-Item -ItemType Directory -Path $dest | Out-Null
    Copy-Item $src $dest -Recurse
  displayName: 'Combine Frontend + Backend'

# 3️⃣ Install backend dependencies
- script: |
    cd backend
    npm install --production
  displayName: 'Install Backend Dependencies'
  shell: cmd

# 4️⃣ Package backend for deployment
- powershell: |
    Write-Host "Packaging backend..."
    Compress-Archive -Path "backend\*" -DestinationPath "backend.zip" -Force
  displayName: 'Create Deployment Package'

# 5️⃣ Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    appName: '$(webAppName)'
    package: 'backend.zip'
  displayName: 'Deploy to Azure Web App'