# =====================================================
# Azure Pipeline for Backend Docker Build & Push
# =====================================================

trigger:
- main   # run pipeline when changes are pushed to main branch

# Use your self-hosted agent
pool:
  name: 'SelfHostPool'   # 👈 update if your pool name differs

variables:
  # Docker image name (you can change this)
  imageName: 'backend-service'

  # Azure Container Registry name (no .azurecr.io)
  azureContainerRegistry: 'tdasRegistry'   # 👈 replace with your ACR name

steps:
# =====================================================
# Step 1: Check out code
# =====================================================
- task: Checkout@1
  displayName: 'Checkout repository'
  inputs:
    clean: true

# =====================================================
# Step 2: Log in to Azure using Service Principal
# =====================================================
- task: AzureCLI@2
  displayName: 'Azure CLI - Login with Service Principal'
  inputs:
    azureSubscription: ''
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logging into Azure using Service Principal..."
      az login --service-principal \
        -u $(AZURE_SP_APP_ID) \
        -p $(AZURE_SP_PASSWORD) \
        --tenant $(AZURE_SP_TENANT_ID)

# =====================================================
# Step 3: Log in to Azure Container Registry
# =====================================================
- script: |
    echo "Logging into Azure Container Registry..."
    az acr login --name $(azureContainerRegistry)
  displayName: 'Login to ACR'

# =====================================================
# Step 4: Build and Push Docker Image
# =====================================================
- script: |
    echo "Building Docker image..."
    docker build -t $(azureContainerRegistry).azurecr.io/$(imageName):latest .

    echo "Pushing Docker image to ACR..."
    docker push $(azureContainerRegistry).azurecr.io/$(imageName):latest
  displayName: 'Build and Push Docker Image'

# =====================================================
# Step 5: Logout for cleanup
# =====================================================
- script: |
    docker logout $(azureContainerRegistry).azurecr.io
    az logout
  displayName: 'Logout'
